### ISSUE TITLE
Error while reading plugin options: "No module named shell"

### ISSUE THREAD

**Issue by hktalent** [andresriancho/w3af-kali#14]
```
./w3af_console -t http://192.168.10.105:7001/
/usr/lib/python2.7/dist-packages/scipy/spatial/__init__.py:96: ImportWarning: Not importing directory '/usr/lib/python2.7/dist-packages/scipy/spatial/qhull': missing __init__.py
  from .qhull import *
/usr/lib/python2.7/dist-packages/scipy/optimize/_minimize.py:37: ImportWarning: Not importing directory '/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb': missing __init__.py
  from .lbfgsb import _minimize_lbfgsb
It seems that your Python installation does not have all the modules required by the w3af framework. For more information about how to install and debug dependency issues please browse to http://docs.w3af.org/en/latest/install.html
Error while reading plugin options: "No module named shell"
/mytools/w3af#pip install scipy
Requirement already satisfied: scipy in /usr/lib/python2.7/dist-packages (1.1.0)
/mytools/w3af#./w3af_console -t http://192.168.10.105:7001/
/usr/lib/python2.7/dist-packages/scipy/spatial/__init__.py:96: ImportWarning: Not importing directory '/usr/lib/python2.7/dist-packages/scipy/spatial/qhull': missing __init__.py
  from .qhull import *
/usr/lib/python2.7/dist-packages/scipy/optimize/_minimize.py:37: ImportWarning: Not importing directory '/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb': missing __init__.py
  from .lbfgsb import _minimize_lbfgsb
It seems that your Python installation does not have all the modules required by the w3af framework. For more information about how to install and debug dependency issues please browse to http://docs.w3af.org/en/latest/install.html
Error while reading plugin options: "No module named shell"
```

**Comment by andresriancho** [comment]
Never seen that issue, and with the provided information I can't identify the root cause.

Please find this code in w3af:

```python
class pluginsTypeMenu(menu):
    """
        Common menu for all types of plugins.
        The type of plugins is defined by the menu's own name.
    """
    def __init__(self, name, console, w3af, parent):
        menu.__init__(self, name, console, w3af, parent)
        plugins = w3af.plugins.get_plugin_list(name)
        self._plugins = {}  # name to number of options
        for p in plugins:
            try:
                options = self._w3af.plugins.get_plugin_inst(
                    self._name, p).get_options()
            except Exception, e:
                om.out.error('Error while reading plugin options: "%s"' % e)
                sys.exit(-8)
            else:
                self._plugins[p] = len(options)
        self._configs = {}
```

Change it to:

```python
class pluginsTypeMenu(menu):
    """
        Common menu for all types of plugins.
        The type of plugins is defined by the menu's own name.
    """
    def __init__(self, name, console, w3af, parent):
        menu.__init__(self, name, console, w3af, parent)
        plugins = w3af.plugins.get_plugin_list(name)
        self._plugins = {}  # name to number of options
        for p in plugins:
            try:
                options = self._w3af.plugins.get_plugin_inst(
                    self._name, p).get_options()
            except Exception, e:
                raise
                om.out.error('Error while reading plugin options: "%s"' % e)
                sys.exit(-8)
            else:
                self._plugins[p] = len(options)
        self._configs = {}
```

Run w3af again, and show me the output.

**Comment by hktalent** [comment]
```
#uname -a
Linux 36959e49a21c 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 GNU/Linux
#cat /etc/issue
Kali GNU/Linux Rolling \n \l
```

```
#grep -R "class pluginsTypeMenu" .
./w3af/core/ui/console/plugins.py:class pluginsTypeMenu(menu):

#vi ./w3af/core/ui/console/plugins.py

find
def __init__(self, name, console, w3af, parent):
        menu.__init__(self, name, console, w3af, parent)
        types = w3af.plugins.get_plugin_types()
        self._children = {}

        self._load_help('plugins')

        for t in types:
            self.addChild(t, pluginsTypeMenu)
#            self._help.add_help_entry(t, "List %s plugins" % t, 'plugins')
        self.__loadPluginTypesHelp(types)

#        self._help.add_help_entry('list', "List plugins by their type", 'commands')
#        self._help.add_help_entry('config', "Config plugins (same as <type> config>)", 'commands')

change to
 def __init__(self, name, console, w3af, parent):
        menu.__init__(self, name, console, w3af, parent)
        plugins = w3af.plugins.get_plugin_list(name)
        self._plugins = {}  # name to number of options
        for p in plugins:
            try:
                options = self._w3af.plugins.get_plugin_inst(
                    self._name, p).get_options()
            except Exception, e:
                raise
                om.out.error('Error while reading plugin options: "%s"' % e)
                sys.exit(-8)
            else:
                self._plugins[p] = len(options)
        self._configs = {}

/mytools/w3af-kali#./w3af_console -t http://erp.xxx.com:8082/
Traceback (most recent call last):
  File "./w3af_console", line 13, in <module>
    dependency_check()
  File "/root/mytools/w3af-kali/w3af/core/controllers/dependency_check/dependency_check.py", line 69, in dependency_check
    pip_distributions = pip.get_installed_distributions()
AttributeError: 'module' object has no attribute 'get_installed_distributions'


origin	https://github.com/andresriancho/w3af-kali.git (fetch)



```
