### ISSUE TITLE
fix?     from pip import get_installed_distributions

### ISSUE THREAD

**Issue by hktalent** [andresriancho/w3af-kali#15]
#14 
```
  #pip install --upgrade pip
  #./w3af_console
Traceback (most recent call last):
  File "./w3af_console", line 13, in <module>
    dependency_check()
  File "/root/mytools/w3af-kali/w3af/core/controllers/dependency_check/dependency_check.py", line 69, in dependency_check
    pip_distributions = pip.get_installed_distributions()
AttributeError: 'module' object has no attribute 'get_installed_distributions'
# pip install pip===9.0.3

#./w3af_console
It seems that your Python installation doesn't have all the modules required by the w3af framework. For more information about how to install and debug dependency issues please browse to http://docs.w3af.org/en/latest/install.html
Error while reading plugin options: "No module named shell"

fix:
if pip.__version__ >= "10.0.0":
    from pip._internal.utils.misc import get_installed_distributions
else:
    from pip import get_installed_distributions

```
You are using pip version 9.0.3, however version 18.1 is available.

**Comment by andresriancho** [comment]
You should use w3af from https://github.com/andresriancho/w3af

https://github.com/andresriancho/w3af-kali is not meant to be used by final users.
